### ISSUE TITLE
Installer Request

### ISSUE THREAD

**Issue by tjferry14** [JadedTuna/pythonista-installers#1]
It would be pretty cool to see a version of this running in Pythonista.

https://github.com/PacketPerception/pychievements

**Comment by JadedTuna** [comment]
@tjferry14, it is pretty easy to write script to download pychievements... But do you also need clint? If yes, it is going to be harder :)

**Comment by JadedTuna** [comment]
@tjferry14, anyway, here is the installer for pychievements: [pychievements-installer.py](https://github.com/Vik2015/pythonista-installers/blob/master/pychievements-installer.py). Also, don't forget to download [pypi.py](https://github.com/Vik2015/pythonista-installers/blob/master/pypi.py)!

**Comment by tjferry14** [comment]
Thanks!
